document.write('      <ul>');
document.write('     <li>');
document.write('       <h2><span class="en">Technical Resources</span>');
document.write('      </h2>');
document.write('        <ul>');
document.write('        <li class="toggle-list">');
document.write('        <div><a href="/resources/browser.html?tag=tutorial">');
document.write('               <span class="en">Tutorials</span>');
document.write('               <span class="de" style="display:none">Lernprogramme</span>');
document.write('              <span class="es" style="display:none">Tutoriales</span>');
document.write('               <span class="fr" style="display:none">Didacticiels</span>');
document.write('               <span class="it" style="display:none">Esercitazioni</span>');
document.write('               <span class="ja" style="display:none">チュートリアル</span>');
document.write('               <span class="zh-CN" style="display:none"></span>');
document.write('               <span class="zh-TW" style="display:none"></span>');
document.write('             </a>');
document.write('        </div>');
document.write('        <ul id="devdoc-nav-tutorial-list">');
document.write('        </ul>');
document.write('      </li>');
document.write('      <li class="toggle-list">');
document.write('        <ul id="devdoc-nav-topic-list">');
document.write('       </ul>');
document.write('      </li>');
document.write('     </ul>');
document.write('   </li>');
document.write('   </ul>');
